version = 0.1
[default.deploy.parameters]
stack_name = "aws-sam-layers-simple"
resolve_s3 = true
s3_prefix = "aws-sam-layers-simple"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
