AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  avione-data-migration

  Sample SAM Template for avione-data-migration

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CommonLayer
      Description: "Layer with common code"
      ContentUri: layers/common-layer/
      CompatibleRuntimes: 
        - nodejs20.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs20.x
    

  DeleteEntities:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete-entities/
      Handler: app.deleteEntitiesHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Layers:
      - !Ref CommonLayer
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.js
        External:
        - "/opt/nodejs/common-layer"

  ImportInvestors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/import-investors/
      Handler: app.importInvestorsHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Layers:
      - !Ref CommonLayer
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.js
        External:
        - "/opt/nodejs/common-layer"

Outputs:
  DeleteEntitiesFunction:
    Description: DeleteEntities Lambda Function ARN
    Value: !GetAtt DeleteEntities.Arn
  ImportInvestorsFunction:
    Description: ImportInvestors Lambda Function ARN
    Value: !GetAtt ImportInvestors.Arn